---
title: "PCR and PLS Margaret"
format: html
editor: visual
---

```{r message=FALSE}
library(tidyverse)
library(pls)
```

```{r message=FALSE}
getwd()

ppp <- read_csv("PPP details.csv")
```

```{r}
# Cleaning
# unique(ppp$`*Loan Status`)
# colnames(ppp)
glimpse(ppp)
ppp_2 <- ppp %>%
  na.omit() %>% # Drop NA's
  mutate(delta = ifelse(`Loan amount` - `Amount forgiven` <= 0, 1, 0)) %>% #Coerce a categorical variable to help with prediction.
  select(Payroll, Rent, Utilities, `Health Care`, `Mortgage Interest`, `Debt Interest`, `Jobs reported`, delta, Borrower)
glimpse(ppp_2)

ppp_3 <- ppp %>%
  na.omit() %>% # Drop NA's
  


# ppp_2$delta <- as.numeric(as.factor(ppp_2$delta))
 str(ppp_2)
```

# Linear Regression

```{r}
set.seed(123)
x_train <- stats::model.matrix(lm(delta ~ ., data = ppp_2[Z, ]))
y_train <- ppp_2$delta[Z]
x_test <-  stats::model.matrix(lm(delta ~ ., data = ppp_2[-Z, ]))                  
y_test <- ppp_2$delta[-Z]

lr <- glmnet::glmnet(x_train, y_train) 
lr_cv <- glmnet::cv.glmnet(x_train, y_train)
best_lambda_lr <- lr_cv$lambda.1se
plot(lr_cv)
coef(lr_cv)

# Lasso Regression Prediction MSE
lr_pred <- predict(lr, s = best_lambda_lr, newx = x_test)
mean((lr_pred - y_test)^2)
```

# PCR 

```{r}
skimr::skim(ppp)
```

```{r}
ppp %>% 
  filter(`Loan amount`,`Amount forgiven`, `*Loan Status`, `Date approved`, `Date forgiven`, Payroll, Rent, Utilities,`Health Care`, `Mortgage Interest`, `Debt Interest`, `Refinancing EIDL`,`Lender name`, `Business type`, Industry, `Age of business`, `Borrower city`)


set.seed(1234)
pcr_reg <- pcr(`Loan amount` ~ `Amount forgiven`+ `*Loan Status`+ `Date approved`+ `Date forgiven`+ Payroll+Rent+Utilities+`Health Care`+ `Mortgage Interest`+ `Debt Interest`+ `Refinancing EIDL`+`Lender name`+ `Business type`+ Industry+ `Age of business`+ `Borrower city`, data = ppp, scale = TRUE,
               validation = "CV", na.exclude(ppp))
summary(pcr_reg)


set.seed(1234)
pcr_reg2 <- pcr(`Amount forgiven` ~ `*Loan Status`+ `Date approved`+ `Date forgiven`+Payroll+Rent+Utilities+`Health Care`+`Mortgage Interest`+ `Debt Interest`+ `Refinancing EIDL`+ Industry+ `Age of business`, data = ppp_3, scale = TRUE,
               validation = "CV")
summary(pcr_reg2)

#no business type
#no lender names
```

PLS

```{r}
set.seed(1234)
pls_reg <- plsr(`Amount forgiven` ~ `*Loan Status`+ `Date approved`+ `Date forgiven`+Payroll+Rent+Utilities+`Health Care`+`Mortgage Interest`+ `Debt Interest`+ `Refinancing EIDL`+ Industry+ `Age of business`, data = ppp_3, scale = TRUE, ncomp = 34,
                validation = "CV")
summary(pls_reg)
```
