---
title: "Peter code work"
format: html
editor: visual
---

```{r message=FALSE}
library(tidyverse)
library(car)
library(class)
```

```{r message=FALSE}
getwd()

ppp <- read_csv("PPP details.csv")

# trial
```

```{r}
# Cleaning
# unique(ppp$`*Loan Status`)
# colnames(ppp)
glimpse(ppp)
ppp_2 <- ppp %>%
  na.omit() %>% # Drop NA's
  mutate(delta = ifelse(`Loan amount` - `Amount forgiven` <= 0, 1, 0)) %>% #Coerce a categorical variable to help with prediction.
  select(Payroll, Rent, Utilities, `Health Care`, `Mortgage Interest`, `Debt Interest`, `Jobs reported`, delta, Borrower)
glimpse(ppp_2$delta)

summary(ppp$`Debt Interest`)
qplot(`Amount forgiven`, data = ppp, geom = "auto")
qplot(delta, data = ppp_2, geom = "auto")
qplot(`*Loan Status`, data = ppp_2, geom = "auto")
qplot(`Loan amount`, `Lender name`, data = ppp, geom = "auto")
qplot(`Business type`, data = ppp_2, geom = "auto")
table(ppp$Industry)
table(ppp$`Business type`)
# ppp_2$delta <- as.numeric(as.factor(ppp_2$delta))
str(ppp_2)
```

# Linear Regression

```{r}
set.seed(123)
x_train <- stats::model.matrix(lm(delta ~ ., data = ppp_2[Z, ]))
y_train <- ppp_2$delta[Z]
x_test <-  stats::model.matrix(lm(delta ~ ., data = ppp_2[-Z, ]))                  
y_test <- ppp_2$delta[-Z]

lr <- glmnet::glmnet(x_train, y_train) 
lr_cv <- glmnet::cv.glmnet(x_train, y_train)
best_lambda_lr <- lr_cv$lambda.1se
plot(lr_cv)
coef(lr_cv)

# Lasso Regression Prediction MSE
lr_pred <- predict(lr, s = best_lambda_lr, newx = x_test)
mean((lr_pred - y_test)^2)
```

# KNN

```{r}
#?knn()
set.seed(1234)
training_pct <- .70
# with over 25k observations this leaves about 7,500 for testing
Z = sample(nrow(ppp_2), floor(training_pct*nrow(ppp_2)))

Xtrain = ppp_2[Z,] # Our training set x
Ytrain = ppp_2$delta[Z] # Our training set y
Xtest = ppp_2[-Z,]
Ytest = ppp_2$delta[-Z]
knn(Xtrain, Xtest, Ytrain, k = 10, prob = TRUE)

# Initialize data
err_class <- rep(1:100)
tpr <- rep(1:100)
fpr <- rep(1:100)
# run the loop
for (k in 1:100){ # There is something wrong in here.....
Yhat <- knn(Xtrain, Xtest, Ytrain, k = k)
err_class[k] <- mean(Yhat != Ytest) # The prediction is not correct
tpr[k] <- sum(Yhat == 1 & Ytest == 1) / sum(Ytest == 1) # TP/P
fpr[k] <- sum(Yhat == 1 & Ytest == 0) / sum(Ytest == 0) # FP/N
}
ggplot(tibble(err_class, k = 1:100), aes(x = k, y = err_class))
geom_line()
```

# Logistics Regression

# LDA/QDA
