<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Presentation Code Compiled</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Presentation_Code_Compiled_files/libs/clipboard/clipboard.min.js"></script>
<script src="Presentation_Code_Compiled_files/libs/quarto-html/quarto.js"></script>
<script src="Presentation_Code_Compiled_files/libs/quarto-html/popper.min.js"></script>
<script src="Presentation_Code_Compiled_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Presentation_Code_Compiled_files/libs/quarto-html/anchor.min.js"></script>
<link href="Presentation_Code_Compiled_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Presentation_Code_Compiled_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Presentation_Code_Compiled_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Presentation_Code_Compiled_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Presentation_Code_Compiled_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Presentation Code Compiled</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(class)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(leaps)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmnet)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(pls)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(e1071)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tree)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"PPP details.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 29,511
Columns: 29
$ Borrower                          &lt;chr&gt; "CAVA MEZZE GRILL, LLC", "AMERICAN C…
$ `Loan amount`                     &lt;dbl&gt; 10000000, 10000000, 9026082, 8915913…
$ `Amount forgiven`                 &lt;dbl&gt; 10116389, 10115278, 5910159, 9053194…
$ `*Loan Status`                    &lt;chr&gt; "Paid in Full", "Paid in Full", "Exe…
$ `Date approved`                   &lt;date&gt; 2020-04-08, 2020-04-28, 2021-02-11,…
$ `Date forgiven`                   &lt;date&gt; 2021-06-11, 2021-06-25, 2022-02-17,…
$ Payroll                           &lt;dbl&gt; 10000000, 10000000, 9026077, 6584058…
$ Rent                              &lt;dbl&gt; 0, 0, 0, 2331855, 0, 0, 0, 0, 0, 0, …
$ Utilities                         &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 667…
$ `Health Care`                     &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ `Mortgage Interest`               &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 333…
$ `Debt Interest`                   &lt;dbl&gt; 0e+00, 0e+00, 0e+00, 0e+00, 0e+00, 1…
$ `Refinancing EIDL`                &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ `Not Provided`                    &lt;dbl&gt; 0, 0, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, …
$ `Lender name`                     &lt;chr&gt; "Truist Bank", "City First Bank, Nat…
$ `Loan number`                     &lt;dbl&gt; 7727377003, 8934987202, 7310038410, …
$ `Business type`                   &lt;chr&gt; "Limited  Liability Company(LLC)", "…
$ Industry                          &lt;chr&gt; "Accommodation and Food Services", "…
$ `Industry (detailed)`             &lt;chr&gt; "Full-Service Restaurants", "Volunta…
$ `Age of business`                 &lt;chr&gt; "Existing or more than 2 years old",…
$ `Borrower address`                &lt;chr&gt; "702 H Street NW", "2400 N Street, N…
$ `Borrower city`                   &lt;chr&gt; "WASHINGTON", "Washington", "Washing…
$ `Borrower state`                  &lt;chr&gt; "DC", "DC", "DC", "DC", "DC", "DC", …
$ `Borrower zip`                    &lt;chr&gt; "20001-3734", "20037", "20003-3302",…
$ `Borrower county and state`       &lt;chr&gt; "DC-DISTRICT OF COLUMBIA", "DC-DISTR…
$ `Borrower congressional district` &lt;chr&gt; "DC", "DC", "DC", "DC", "DC", "DC", …
$ `Jobs reported`                   &lt;dbl&gt; 500, 465, 500, 493, 345, 408, 486, 5…
$ Gender                            &lt;chr&gt; "Unanswered", "Unanswered", "Unanswe…
$ Race                              &lt;chr&gt; "Unanswered", "Unanswered", "Unanswe…</code></pre>
</div>
</div>
<section id="cleaning" class="level3">
<h3 class="anchored" data-anchor-id="cleaning">Cleaning</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>ppp <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">type_mod =</span> <span class="fu">case_when</span>(</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"501(c)3 – Non Profit"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"501(c)6 – Non Profit Membership"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Non-Profit Childcare Center"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Non-Profit Organization"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Professional Association"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Housing Co-op"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Cooperative"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Corporation"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Limited  Liability Company(LLC)"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Limited Liability Partnership"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Qualified Joint-Venture (spouses)"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Subchapter S Corporation"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Tribal Concerns"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Joint Venture"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Trust"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Independent contractors"</span> <span class="sc">~</span> <span class="st">"For-profit, Individual"</span>,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Single Member LLC"</span> <span class="sc">~</span> <span class="st">"For-profit, Individual"</span>,</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Sole Proprietorship"</span> <span class="sc">~</span> <span class="st">"For-profit, Individual"</span>,</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Self-Employed Individuals"</span> <span class="sc">~</span> <span class="st">"For-profit, Individual"</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Amount forgiven</span><span class="st">`</span>, Payroll, Rent, Utilities,</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Health Care</span><span class="st">`</span>, <span class="st">`</span><span class="at">Mortgage Interest</span><span class="st">`</span>, <span class="st">`</span><span class="at">Debt Interest</span><span class="st">`</span>, Gender, Race, <span class="st">`</span><span class="at">Refinancing EIDL</span><span class="st">`</span>, Industry,<span class="st">`</span><span class="at">Jobs reported</span><span class="st">`</span>, type_mod, <span class="st">`</span><span class="at">*Loan Status</span><span class="st">`</span>, <span class="st">`</span><span class="at">Date approved</span><span class="st">`</span>, <span class="st">`</span><span class="at">Date forgiven</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">type_mod =</span> <span class="fu">as_factor</span>(type_mod),</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">Industry =</span> <span class="fu">as_factor</span>(Industry),</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">Gender =</span> <span class="fu">as_factor</span>(Gender),</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">Race =</span> <span class="fu">as_factor</span>(Race)</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ppp) <span class="ot">&lt;-</span>  stringr<span class="sc">::</span><span class="fu">str_replace_all</span>(<span class="fu">names</span>(ppp), <span class="st">" "</span>, <span class="st">"_"</span>)</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 23,678
Columns: 16
$ Amount_forgiven   &lt;dbl&gt; 10116389, 10115278, 5910159, 9053194, 8309511, 78071…
$ Payroll           &lt;dbl&gt; 10000000, 10000000, 9026077, 6584058, 8202873, 70000…
$ Rent              &lt;dbl&gt; 0, 0, 0, 2331855, 0, 0, 0, 0, 0, 0, 333532, 0, 0, 0,…
$ Utilities         &lt;dbl&gt; 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 667062, 0, 0, 0, 0, 0,…
$ Health_Care       &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Mortgage_Interest &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 333531, 0, 0, 0, 0, 0,…
$ Debt_Interest     &lt;dbl&gt; 0e+00, 0e+00, 0e+00, 0e+00, 0e+00, 1e+06, 0e+00, 0e+…
$ Gender            &lt;fct&gt; Unanswered, Unanswered, Unanswered, Unanswered, Unan…
$ Race              &lt;fct&gt; Unanswered, Unanswered, Unanswered, Unanswered, Unan…
$ Refinancing_EIDL  &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ Industry          &lt;fct&gt; "Accommodation and Food Services", "Other Services (…
$ Jobs_reported     &lt;dbl&gt; 500, 465, 500, 493, 345, 408, 486, 500, 227, 316, 29…
$ type_mod          &lt;fct&gt; "For-profit, group", "Non-Profit", "For-profit, grou…
$ `*Loan_Status`    &lt;chr&gt; "Paid in Full", "Paid in Full", "Exemption 4", "Paid…
$ Date_approved     &lt;date&gt; 2020-04-08, 2020-04-28, 2021-02-11, 2020-04-28, 202…
$ Date_forgiven     &lt;date&gt; 2021-06-11, 2021-06-25, 2022-02-17, 2021-11-18, 202…</code></pre>
</div>
</div>
</section>
<section id="exploration" class="level3">
<h3 class="anchored" data-anchor-id="exploration">Exploration</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> Amount_forgiven       Payroll              Rent             Utilities        
 Min.   :       5   Min.   :       0   Min.   :      0.0   Min.   :      0.0  
 1st Qu.:   14834   1st Qu.:   14643   1st Qu.:      0.0   1st Qu.:      0.0  
 Median :   21189   Median :   21345   Median :      0.0   Median :      0.0  
 Mean   :  125679   Mean   :  125016   Mean   :    830.8   Mean   :    627.7  
 3rd Qu.:   91941   3rd Qu.:   91788   3rd Qu.:      0.0   3rd Qu.:      1.0  
 Max.   :10116389   Max.   :10000000   Max.   :2331855.0   Max.   :1550000.0  
                                                                              
  Health_Care       Mortgage_Interest  Debt_Interest               Gender     
 Min.   :     0.0   Min.   :     0.0   Min.   :0.00e+00   Unanswered  :14585  
 1st Qu.:     0.0   1st Qu.:     0.0   1st Qu.:0.00e+00   Male Owned  : 5767  
 Median :     0.0   Median :     0.0   Median :0.00e+00   Female Owned: 3326  
 Mean   :   263.7   Mean   :   255.2   Mean   :6.42e+01                       
 3rd Qu.:     0.0   3rd Qu.:     0.0   3rd Qu.:0.00e+00                       
 Max.   :542925.0   Max.   :600000.0   Max.   :1.00e+06                       
                                                                              
                                        Race       Refinancing_EIDL  
 Unanswered                               :18030   Min.   :    0.00  
 Asian                                    :  907   1st Qu.:    0.00  
 Black or African American                : 2735   Median :    0.00  
 White                                    : 1957   Mean   :    7.55  
 American Indian or Alaska Native         :   35   3rd Qu.:    0.00  
 Native Hawaiian or Other Pacific Islander:   14   Max.   :60000.00  
                                                                     
                                             Industry    Jobs_reported   
 Professional, Scientific, and Technical Services:5139   Min.   :  1.00  
 Other Services (except Public Administration)   :4109   1st Qu.:  1.00  
 Accommodation and Food Services                 :2861   Median :  2.00  
 Health Care and Social Assistance               :2212   Mean   : 11.36  
 Retail Trade                                    :1540   3rd Qu.:  9.00  
 Transportation and Warehousing                  :1413   Max.   :500.00  
 (Other)                                         :6404                   
                   type_mod     *Loan_Status       Date_approved       
 For-profit, group     :13241   Length:23678       Min.   :2020-04-03  
 Non-Profit            : 2951   Class :character   1st Qu.:2020-04-30  
 For-profit, Individual: 7486   Mode  :character   Median :2021-01-23  
                                                   Mean   :2020-10-18  
                                                   3rd Qu.:2021-03-20  
                                                   Max.   :2021-06-30  
                                                                       
 Date_forgiven       
 Min.   :2020-10-09  
 1st Qu.:2021-05-11  
 Median :2021-09-01  
 Mean   :2021-08-28  
 3rd Qu.:2021-11-16  
 Max.   :2022-12-30  
                     </code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>car<span class="sc">::</span><span class="fu">vif</span>(<span class="fu">lm</span>(Amount_forgiven <span class="sc">~</span> ., ppp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                      GVIF Df GVIF^(1/(2*Df))
Payroll           3.498362  1        1.870391
Rent              1.064532  1        1.031761
Utilities         1.116663  1        1.056723
Health_Care       1.092341  1        1.045151
Mortgage_Interest 1.164109  1        1.078939
Debt_Interest     1.023104  1        1.011486
Gender            1.960348  2        1.183268
Race              2.072297  5        1.075586
Refinancing_EIDL  1.013980  1        1.006966
Industry          1.741084 19        1.014699
Jobs_reported     3.530434  1        1.878945
type_mod          1.812957  2        1.160371
`*Loan_Status`    1.065033  2        1.015876
Date_approved     2.381459  1        1.543198
Date_forgiven     2.030675  1        1.425018</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>ppp <span class="sc">|&gt;</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> type_mod)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Distribution of Business Type"</span>) <span class="sc">+</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"Business Type"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Presentation_Code_Compiled_files/figure-html/explore-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>ppp <span class="sc">|&gt;</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Amount_forgiven)) <span class="sc">+</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_histogram</span>() <span class="sc">+</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ggtitle</span>(<span class="st">"Distribution of Amount Forgiven"</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">xlab</span>(<span class="st">"Amount Forgiven"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Presentation_Code_Compiled_files/figure-html/explore-2.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#remove 3 variables b/c too many levels</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co">#GGally::ggpairs(ppp %&gt;% select(-Business_type, -Industry, -Borrower_zip))</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>ppp <span class="sc">|&gt;</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> type_mod, <span class="at">y =</span> Health_Care)) <span class="sc">+</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Presentation_Code_Compiled_files/figure-html/explore-3.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="regression" class="level2">
<h2 class="anchored" data-anchor-id="regression">Regression</h2>
<section id="stepwise" class="level3">
<h3 class="anchored" data-anchor-id="stepwise">Stepwise</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#forward using type_mod</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>reg_full <span class="ot">&lt;-</span> <span class="fu">lm</span>(Amount_forgiven <span class="sc">~</span> ., <span class="at">data =</span> ppp)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>reg_null <span class="ot">&lt;-</span> <span class="fu">lm</span>(Amount_forgiven <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> ppp)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>step_out_f <span class="ot">&lt;-</span> <span class="fu">step</span>(reg_null, </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">scope =</span> <span class="fu">list</span>(<span class="at">lower =</span> reg_null, <span class="at">upper =</span> reg_full),</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">method =</span> <span class="st">"forward"</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>                    <span class="at">trace =</span> <span class="dv">0</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co">#forward results</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(step_out_f)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Amount_forgiven ~ Payroll + Rent + Utilities + `*Loan_Status` + 
    Health_Care + Debt_Interest + Mortgage_Interest + Jobs_reported + 
    type_mod + Refinancing_EIDL, data = ppp)

Residuals:
     Min       1Q   Median       3Q      Max 
-2849981    -2875     -868     -440   452930 

Coefficients:
                                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                    -1.173e+05  5.483e+03 -21.388  &lt; 2e-16 ***
Payroll                         9.879e-01  1.482e-03 666.467  &lt; 2e-16 ***
Rent                            1.089e+00  1.565e-02  69.577  &lt; 2e-16 ***
Utilities                       9.362e-01  1.794e-02  52.182  &lt; 2e-16 ***
`*Loan_Status`Exemption 4       3.140e+04  6.071e+03   5.171 2.34e-07 ***
`*Loan_Status`Paid in Full      1.209e+05  5.489e+03  22.030  &lt; 2e-16 ***
Health_Care                     1.224e+00  4.298e-02  28.479  &lt; 2e-16 ***
Debt_Interest                   1.038e+00  4.345e-02  23.899  &lt; 2e-16 ***
Mortgage_Interest               6.106e-01  3.343e-02  18.263  &lt; 2e-16 ***
Jobs_reported                  -1.414e+02  1.657e+01  -8.531  &lt; 2e-16 ***
type_modNon-Profit              2.025e+03  8.950e+02   2.262  0.02370 *  
type_modFor-profit, Individual -2.545e+03  6.418e+02  -3.965 7.36e-05 ***
Refinancing_EIDL                1.960e+00  6.678e-01   2.935  0.00334 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 43530 on 23665 degrees of freedom
Multiple R-squared:  0.9851,    Adjusted R-squared:  0.9851 
F-statistic: 1.301e+05 on 12 and 23665 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The stepwise regression found that payroll, rent, utilities, loan status, healthcare, debt interest, mortgage interest, jobs reported, refinancing EIDL, and business type modified were significant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>reg_k10 <span class="ot">&lt;-</span> <span class="fu">glm</span>(Amount_forgiven <span class="sc">~</span> Payroll <span class="sc">+</span> Rent <span class="sc">+</span> Utilities <span class="sc">+</span> Health_Care <span class="sc">+</span> Debt_Interest <span class="sc">+</span> Mortgage_Interest <span class="sc">+</span> Jobs_reported <span class="sc">+</span> type_mod <span class="sc">+</span> Date_forgiven <span class="sc">+</span> Date_approved, <span class="at">data =</span> ppp)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>regCVk10 <span class="ot">&lt;-</span> boot<span class="sc">::</span><span class="fu">cv.glm</span>(ppp, reg_k10, <span class="at">K =</span> <span class="dv">10</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>regCVk10<span class="sc">$</span>delta[<span class="dv">2</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2106947766</code></pre>
</div>
</div>
<p>The MSE for stepwise is 22106947766.</p>
</section>
<section id="lasso-and-ridge" class="level3">
<h3 class="anchored" data-anchor-id="lasso-and-ridge">LASSO and Ridge</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">model.matrix</span>(<span class="fu">lm</span>(Amount_forgiven <span class="sc">~</span> ., ppp))[,<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>ridge_ppp <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(X, ppp<span class="sc">$</span>Amount_forgiven, <span class="at">alpha =</span> <span class="dv">0</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ridge_ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Presentation_Code_Compiled_files/figure-html/ridge-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>ridge_ppp<span class="sc">$</span>lambda.min</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35197.64</code></pre>
</div>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(ridge_ppp<span class="sc">$</span>cvm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3777754837</code></pre>
</div>
</div>
<p>The MSE for ridge regression is 3777754837.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>lasso_ppp <span class="ot">&lt;-</span> <span class="fu">cv.glmnet</span>(X, ppp<span class="sc">$</span>Amount_forgiven, <span class="at">alpha =</span> <span class="dv">1</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(lasso_ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Presentation_Code_Compiled_files/figure-html/lasso-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>lasso_ppp<span class="sc">$</span>lambda<span class="fl">.1</span>se</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10260.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(lasso_ppp<span class="sc">$</span>cvm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2002900584</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">coef</span>(lasso_ppp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>41 x 1 sparse Matrix of class "dgCMatrix"
                                                                                           s1
(Intercept)                                                                      4844.5337598
Payroll                                                                             0.9589994
Rent                                                                                0.7051543
Utilities                                                                           0.4686261
Health_Care                                                                         0.2422003
Mortgage_Interest                                                                   .        
Debt_Interest                                                                       .        
GenderMale Owned                                                                    .        
GenderFemale Owned                                                                  .        
RaceAsian                                                                           .        
RaceBlack or African American                                                       .        
RaceWhite                                                                           .        
RaceAmerican Indian or Alaska Native                                                .        
RaceNative Hawaiian or Other Pacific Islander                                       .        
Refinancing_EIDL                                                                    .        
IndustryOther Services (except Public Administration)                               .        
IndustryReal Estate and Rental and Leasing                                          .        
IndustryProfessional, Scientific, and Technical Services                            .        
IndustryConstruction                                                                .        
IndustryAdministrative and Support and Waste Management and Remediation Services    .        
IndustryEducational Services                                                        .        
IndustryAgriculture, Forestry, Fishing and Hunting                                  .        
IndustryHealth Care and Social Assistance                                           .        
IndustryRetail Trade                                                                .        
IndustryInformation                                                                 .        
IndustryArts, Entertainment, and Recreation                                         .        
IndustryManagement of Companies and Enterprises                                     .        
IndustryPublic Administration                                                       .        
IndustryFinance and Insurance                                                       .        
IndustryManufacturing                                                               .        
IndustryWholesale Trade                                                             .        
IndustryUtilities                                                                   .        
IndustryTransportation and Warehousing                                              .        
IndustryMining, Quarrying, and Oil and Gas Extraction                               .        
Jobs_reported                                                                       .        
type_modNon-Profit                                                                  .        
type_modFor-profit, Individual                                                      .        
`*Loan_Status`Exemption 4                                                           .        
`*Loan_Status`Paid in Full                                                          .        
Date_approved                                                                       .        
Date_forgiven                                                                       .        </code></pre>
</div>
</div>
<p>The MSE for LASSO is 2002900584. The non-zero predictors are payroll, rent, utilities, and health care.</p>
</section>
<section id="pcr-and-pls" class="level3">
<h3 class="anchored" data-anchor-id="pcr-and-pls">PCR and PLS</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co">#screeplot</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">screeplot</span>(</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prcomp</span>(</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">model.matrix</span>(<span class="fu">lm</span>(Amount_forgiven <span class="sc">~</span> ., <span class="at">data =</span> ppp))</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>) <span class="co">#indicates need to scale</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Presentation_Code_Compiled_files/figure-html/pca-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co">#PCR</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ppp) <span class="ot">&lt;-</span>  stringr<span class="sc">::</span><span class="fu">str_replace_all</span>(<span class="fu">names</span>(ppp), <span class="st">" "</span>, <span class="st">"_"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>pcr_ppp <span class="ot">&lt;-</span>  <span class="fu">pcr</span>(Amount_forgiven <span class="sc">~</span> ., </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> ppp, </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">scale =</span> <span class="cn">TRUE</span>,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>                <span class="at">validation =</span> <span class="st">"CV"</span>)</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(pcr_ppp)</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(<span class="fu">as.numeric</span>(<span class="fu">MSEP</span>(pcr_ppp, <span class="at">estimate =</span> <span class="st">"CV"</span>)<span class="sc">$</span>val)) <span class="sc">-</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40</code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(<span class="fu">as.numeric</span>(<span class="fu">MSEP</span>(pcr_ppp, <span class="at">estimate =</span> <span class="st">"CV"</span>)<span class="sc">$</span>val))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2041329571</code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co">#PLS</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>pls_ppp <span class="ot">&lt;-</span>  <span class="fu">plsr</span>(Amount_forgiven <span class="sc">~</span> ., </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                <span class="at">data =</span> ppp,</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>                <span class="at">scale =</span> <span class="cn">TRUE</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>                <span class="at">validation =</span> <span class="st">"CV"</span>)</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="co">#summary(pls_ppp)</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(<span class="fu">as.numeric</span>(<span class="fu">MSEP</span>(pls_ppp, <span class="at">estimate =</span> <span class="st">"CV"</span>)<span class="sc">$</span>val)) <span class="sc">-</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 11</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(<span class="fu">as.numeric</span>(<span class="fu">MSEP</span>(pls_ppp, <span class="at">estimate =</span> <span class="st">"CV"</span>)<span class="sc">$</span>val))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2040856908</code></pre>
</div>
</div>
<p>The MSE for PCR is 2041329571 with 40 principal components. The MSE for PLS is 2040856908 with 11 principal components.</p>
</section>
</section>
<section id="classification" class="level2">
<h2 class="anchored" data-anchor-id="classification">Classification</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>ppp_c <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">type_mod =</span> <span class="fu">case_when</span>(</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"501(c)3 – Non Profit"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"501(c)6 – Non Profit Membership"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Non-Profit Childcare Center"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Non-Profit Organization"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Professional Association"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Housing Co-op"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Cooperative"</span> <span class="sc">~</span> <span class="st">"Non-Profit"</span>,</span>
<span id="cb39-10"><a href="#cb39-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Corporation"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb39-11"><a href="#cb39-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Limited  Liability Company(LLC)"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb39-12"><a href="#cb39-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Limited Liability Partnership"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb39-13"><a href="#cb39-13" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Qualified Joint-Venture (spouses)"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb39-14"><a href="#cb39-14" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Subchapter S Corporation"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb39-15"><a href="#cb39-15" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Tribal Concerns"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb39-16"><a href="#cb39-16" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Joint Venture"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb39-17"><a href="#cb39-17" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Trust"</span> <span class="sc">~</span> <span class="st">"For-profit, group"</span>,</span>
<span id="cb39-18"><a href="#cb39-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Independent contractors"</span> <span class="sc">~</span> <span class="st">"For-profit, Individual"</span>,</span>
<span id="cb39-19"><a href="#cb39-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Single Member LLC"</span> <span class="sc">~</span> <span class="st">"For-profit, Individual"</span>,</span>
<span id="cb39-20"><a href="#cb39-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Sole Proprietorship"</span> <span class="sc">~</span> <span class="st">"For-profit, Individual"</span>,</span>
<span id="cb39-21"><a href="#cb39-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Business type</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Self-Employed Individuals"</span> <span class="sc">~</span> <span class="st">"For-profit, Individual"</span></span>
<span id="cb39-22"><a href="#cb39-22" aria-hidden="true" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span></span>
<span id="cb39-23"><a href="#cb39-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(</span>
<span id="cb39-24"><a href="#cb39-24" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Amount forgiven</span><span class="st">`</span>, Payroll, Rent, Utilities,</span>
<span id="cb39-25"><a href="#cb39-25" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Health Care</span><span class="st">`</span>, <span class="st">`</span><span class="at">Mortgage Interest</span><span class="st">`</span>, <span class="st">`</span><span class="at">Debt Interest</span><span class="st">`</span>, <span class="st">`</span><span class="at">Refinancing EIDL</span><span class="st">`</span>, Industry,<span class="st">`</span><span class="at">Jobs reported</span><span class="st">`</span>, type_mod, <span class="st">`</span><span class="at">*Loan Status</span><span class="st">`</span>, <span class="st">`</span><span class="at">Date approved</span><span class="st">`</span>, <span class="st">`</span><span class="at">Date forgiven</span><span class="st">`</span>, Gender, Race, <span class="st">`</span><span class="at">Loan amount</span><span class="st">`</span>, <span class="st">`</span><span class="at">Age of business</span><span class="st">`</span>) <span class="sc">%&gt;%</span></span>
<span id="cb39-26"><a href="#cb39-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb39-27"><a href="#cb39-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">type_mod =</span> <span class="fu">as_factor</span>(type_mod),</span>
<span id="cb39-28"><a href="#cb39-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">Industry =</span> <span class="fu">as_factor</span>(Industry),</span>
<span id="cb39-29"><a href="#cb39-29" aria-hidden="true" tabindex="-1"></a>    <span class="at">Gender =</span> <span class="fu">as_factor</span>(Gender),</span>
<span id="cb39-30"><a href="#cb39-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">Race =</span> <span class="fu">as_factor</span>(Race),</span>
<span id="cb39-31"><a href="#cb39-31" aria-hidden="true" tabindex="-1"></a>    <span class="st">`</span><span class="at">Age of business</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">as_factor</span>(<span class="st">`</span><span class="at">Age of business</span><span class="st">`</span>)</span>
<span id="cb39-32"><a href="#cb39-32" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb39-33"><a href="#cb39-33" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb39-34"><a href="#cb39-34" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(ppp_c) <span class="ot">&lt;-</span>  stringr<span class="sc">::</span><span class="fu">str_replace_all</span>(<span class="fu">names</span>(ppp_c), <span class="st">" "</span>, <span class="st">"_"</span>)</span>
<span id="cb39-35"><a href="#cb39-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-36"><a href="#cb39-36" aria-hidden="true" tabindex="-1"></a>ppp_c <span class="ot">&lt;-</span> ppp_c <span class="sc">|&gt;</span> <span class="fu">select</span>(type_mod, </span>
<span id="cb39-37"><a href="#cb39-37" aria-hidden="true" tabindex="-1"></a>                         Gender, </span>
<span id="cb39-38"><a href="#cb39-38" aria-hidden="true" tabindex="-1"></a>                         Industry, </span>
<span id="cb39-39"><a href="#cb39-39" aria-hidden="true" tabindex="-1"></a>                         Age_of_business,</span>
<span id="cb39-40"><a href="#cb39-40" aria-hidden="true" tabindex="-1"></a>                         Race, </span>
<span id="cb39-41"><a href="#cb39-41" aria-hidden="true" tabindex="-1"></a>                         Jobs_reported, </span>
<span id="cb39-42"><a href="#cb39-42" aria-hidden="true" tabindex="-1"></a>                         Loan_amount)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="knn" class="level3">
<h3 class="anchored" data-anchor-id="knn">KNN</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>ppp_k <span class="ot">&lt;-</span> ppp_c <span class="sc">|&gt;</span> <span class="fu">mutate</span>(</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Gender =</span> <span class="fu">as.numeric</span>(Gender),</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Race =</span> <span class="fu">as.numeric</span>(Race),</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Age_of_business =</span> <span class="fu">as.numeric</span>(Age_of_business),</span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Industry =</span> <span class="fu">as.numeric</span>(Industry)</span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a><span class="co">#?knn()</span></span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>training_pct <span class="ot">&lt;-</span> .<span class="dv">75</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">=</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(ppp_k), <span class="fu">floor</span>(training_pct<span class="sc">*</span><span class="fu">nrow</span>(ppp_k)))</span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a>Xtrain <span class="ot">=</span> ppp_k[Z, <span class="fu">c</span>(<span class="st">"Race"</span>, <span class="st">"Gender"</span>, <span class="st">"Age_of_business"</span>, <span class="st">"Industry"</span>, <span class="st">"Jobs_reported"</span>, <span class="st">"Loan_amount"</span>)] <span class="co"># Our training set x</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a>Ytrain <span class="ot">=</span> ppp_k<span class="sc">$</span>type_mod[Z] <span class="co"># Our training set y</span></span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a>Xtest <span class="ot">=</span> ppp_k[<span class="sc">-</span>Z, <span class="fu">c</span>(<span class="st">"Race"</span>, <span class="st">"Gender"</span>, <span class="st">"Age_of_business"</span>, <span class="st">"Industry"</span>, <span class="st">"Jobs_reported"</span>, <span class="st">"Loan_amount"</span>)]</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a>Ytest <span class="ot">=</span> ppp_k<span class="sc">$</span>type_mod[<span class="sc">-</span>Z]</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a>Yhat <span class="ot">&lt;-</span> <span class="fu">knn</span>(Xtrain, Xtest, Ytrain, <span class="at">k =</span> <span class="dv">10</span>, <span class="at">prob =</span> <span class="cn">TRUE</span>)</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Ytest, Yhat)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        Yhat
Ytest                    For-profit, group Non-Profit For-profit, Individual
  For-profit, group                   2565        116                    643
  Non-Profit                           615         53                     43
  For-profit, Individual               553          7                   1325</code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> (<span class="fu">table</span>(Ytest, Yhat)[<span class="dv">1</span>, <span class="dv">1</span>] <span class="sc">+</span> <span class="fu">table</span>(Ytest, Yhat)[<span class="dv">2</span>, <span class="dv">2</span>] <span class="sc">+</span> <span class="fu">table</span>(Ytest, Yhat)[<span class="dv">3</span>, <span class="dv">3</span>])<span class="sc">/</span>((<span class="dv">1</span><span class="sc">-</span>training_pct)<span class="sc">*</span><span class="fu">nrow</span>(ppp_k))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3338964</code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Initialize data</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>err_class <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a><span class="co"># run the loop</span></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>){</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>Yhat <span class="ot">&lt;-</span> <span class="fu">knn</span>(Xtrain, Xtest, Ytrain, <span class="at">k =</span> k)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>err_class[k] <span class="ot">&lt;-</span> <span class="fu">mean</span>(Yhat <span class="sc">!=</span> Ytest)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">tibble</span>(err_class, <span class="at">k =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>), <span class="fu">aes</span>(<span class="at">x =</span> k, <span class="at">y =</span> err_class)) <span class="sc">+</span></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Presentation_Code_Compiled_files/figure-html/knn-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">which.min</span>(err_class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 39</code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>err_class[<span class="fu">which.min</span>(err_class)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3206081</code></pre>
</div>
</div>
<p>Optimal <em>k</em> is 39 with an error rate of 32.06%</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 10 K-fold CV on KNN</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>trControl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method  =</span> <span class="st">"cv"</span>,</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">number  =</span> <span class="dv">10</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">train</span>(type_mod <span class="sc">~</span> .,</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">method =</span> <span class="st">"knn"</span>,</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">tuneGrid =</span> <span class="fu">expand.grid</span>(<span class="at">k =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>),</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">trControl =</span> trControl,</span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">metric =</span> <span class="st">"Accuracy"</span>,</span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> ppp_k)</span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-14"><a href="#cb49-14" aria-hidden="true" tabindex="-1"></a>fit<span class="sc">$</span>results <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Accuracy)) <span class="co"># first row is highest accuracy </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    k  Accuracy     Kappa  AccuracySD     KappaSD
1  47 0.6769571 0.3943169 0.005565785 0.008689933
2  28 0.6767042 0.3932814 0.007455309 0.014723220
3  46 0.6764505 0.3933840 0.005477496 0.009293266
4  45 0.6763241 0.3932144 0.005251164 0.009158404
5  40 0.6763234 0.3929742 0.006469746 0.011007304
6  48 0.6763233 0.3930873 0.006280685 0.010435364
7  50 0.6761965 0.3927427 0.005659939 0.009845118
8  44 0.6761548 0.3927330 0.005296592 0.009183356
9  25 0.6760706 0.3920709 0.007824227 0.014625030
10 29 0.6760703 0.3920488 0.007182561 0.014182150
11 26 0.6760285 0.3920669 0.006310825 0.012041608
12 49 0.6760277 0.3926831 0.006162121 0.010329822
13 43 0.6759435 0.3924975 0.005033627 0.008583973
14 27 0.6759016 0.3917903 0.007806784 0.015267295
15 36 0.6757742 0.3916952 0.005896976 0.011022531
16 41 0.6757322 0.3920559 0.006170374 0.010628623
17 42 0.6755635 0.3916673 0.006216965 0.010584454
18 34 0.6755635 0.3909389 0.005448979 0.010282064
19 39 0.6755634 0.3915121 0.006382862 0.010640614
20 21 0.6754793 0.3902911 0.007342024 0.014268639
21 37 0.6754790 0.3908694 0.005008788 0.009242835
22 30 0.6754368 0.3904968 0.005650176 0.011548994
23 35 0.6753519 0.3906686 0.005809227 0.010628550
24 19 0.6752260 0.3899479 0.006701628 0.013198620
25 31 0.6749725 0.3895707 0.006456565 0.013429646
26 24 0.6749719 0.3900813 0.007405778 0.013888889
27 38 0.6749298 0.3902388 0.005856918 0.010299188
28 22 0.6747615 0.3890076 0.006586252 0.013066749
29 33 0.6747612 0.3896146 0.005946179 0.011401112
30 23 0.6746342 0.3892609 0.007985690 0.015063950
31 20 0.6745075 0.3887410 0.007297456 0.014389747
32 32 0.6743814 0.3887104 0.006683799 0.013812033
33 17 0.6738317 0.3870843 0.006492406 0.014127949
34 13 0.6734092 0.3877620 0.006397012 0.011549908
35 18 0.6732828 0.3864241 0.007639021 0.015561001
36 14 0.6727751 0.3858675 0.007049084 0.014538860
37 11 0.6722265 0.3875546 0.009343438 0.017174937
38 16 0.6721843 0.3842952 0.006089713 0.013044711
39 15 0.6719728 0.3835981 0.006627775 0.013412783
40 12 0.6711285 0.3845028 0.006779180 0.011539801
41  9 0.6691010 0.3830001 0.009059029 0.015716524
42 10 0.6676656 0.3805795 0.008290775 0.014986365
43  8 0.6668203 0.3819453 0.007853052 0.013031007
44  7 0.6656389 0.3799087 0.008716842 0.013317358
45  6 0.6591349 0.3725630 0.008499947 0.012624870
46  5 0.6577831 0.3723314 0.009689960 0.015123644
47  4 0.6484918 0.3640774 0.006442379 0.009146924
48  3 0.6452400 0.3628754 0.004861680 0.007541375
49  1 0.6393272 0.3741572 0.005388413 0.008151185
50  2 0.6205759 0.3396366 0.007169677 0.010656233</code></pre>
</div>
</div>
</section>
<section id="lda-and-qda" class="level3">
<h3 class="anchored" data-anchor-id="lda-and-qda">LDA and QDA</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>lda_output <span class="ot">&lt;-</span> MASS<span class="sc">::</span><span class="fu">lda</span>(type_mod <span class="sc">~</span> Gender <span class="sc">+</span> Industry </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>      <span class="sc">+</span> Age_of_business <span class="sc">+</span> Race <span class="sc">+</span> Jobs_reported <span class="sc">+</span> Loan_amount, <span class="at">data =</span> ppp_c, </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>      <span class="at">CV =</span> T)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="co"># create data frame with classifications and true values</span></span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>lda_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Gender =</span> ppp_c<span class="sc">$</span>Gender, </span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Industry =</span> ppp_c<span class="sc">$</span>Industry,</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Age_of_business =</span> ppp_c<span class="sc">$</span>Age_of_business, </span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Race =</span> ppp_c<span class="sc">$</span>Race, </span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Jobs_reported =</span> ppp_c<span class="sc">$</span>Jobs_reported, </span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Loan_amount =</span> ppp_c<span class="sc">$</span>Loan_amount, </span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Class =</span> lda_output<span class="sc">$</span>class) <span class="sc">|&gt;</span> </span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="at">var =</span> <span class="st">"ID"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">as.numeric</span>(ID)) <span class="sc">|&gt;</span> </span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="at">true_q =</span> ppp_c<span class="sc">$</span>type_mod)</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a><span class="co">#LDA Error Rate</span></span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">sum</span>(lda_df<span class="sc">$</span>Class <span class="sc">!=</span> lda_df<span class="sc">$</span>true_q) <span class="sc">/</span> <span class="fu">nrow</span>(ppp_c), <span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 35.75</code></pre>
</div>
</div>
<p>The LDA error rate is 35.76%</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>qda_output <span class="ot">&lt;-</span>  MASS<span class="sc">::</span><span class="fu">qda</span>(type_mod <span class="sc">~</span> Gender <span class="sc">+</span> Jobs_reported <span class="sc">+</span> Loan_amount, <span class="at">data =</span> ppp_c, <span class="at">CV =</span> <span class="cn">TRUE</span>)</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>qda_df <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">Gender =</span> ppp_c<span class="sc">$</span>Gender, </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Jobs_reported =</span> ppp_c<span class="sc">$</span>Jobs_reported, </span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Loan_amount =</span> ppp_c<span class="sc">$</span>Loan_amount, </span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">Class =</span> qda_output<span class="sc">$</span>class) <span class="sc">|&gt;</span> </span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames_to_column</span>(<span class="at">var =</span> <span class="st">"ID"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">as.numeric</span>(ID)) <span class="sc">|&gt;</span> </span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">bind_cols</span>(<span class="at">true_q =</span> ppp_c<span class="sc">$</span>type_mod)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a><span class="co">#QDA Error Rate</span></span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="dv">100</span> <span class="sc">*</span> <span class="fu">sum</span>(qda_df<span class="sc">$</span>Class <span class="sc">!=</span> qda_df<span class="sc">$</span>true_q) <span class="sc">/</span> <span class="fu">nrow</span>(ppp_c), <span class="dv">2</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 51.88</code></pre>
</div>
</div>
<p>The QDA error rate is 51.88%. Race, industry, and age of business had to removed due to rank error. The rank error was investigated below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">filter</span>(ppp_c, type_mod <span class="sc">==</span> <span class="st">"Non-Profit"</span>)<span class="sc">$</span>Race)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
                               Unanswered 
                                     2654 
                                    Asian 
                                       26 
                Black or African American 
                                       82 
                                    White 
                                      185 
         American Indian or Alaska Native 
                                        4 
Native Hawaiian or Other Pacific Islander 
                                        0 </code></pre>
</div>
</div>
</section>
<section id="tree" class="level3">
<h3 class="anchored" data-anchor-id="tree">Tree</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(ppp_c), <span class="fl">0.75</span><span class="sc">*</span><span class="fu">nrow</span>(ppp_c))</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>tree_final <span class="ot">&lt;-</span> <span class="fu">tree</span>(type_mod <span class="sc">~</span> ., <span class="at">data =</span> ppp_c)</span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>tree_final</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>node), split, n, deviance, yval, (yprob)
      * denotes terminal node

 1) root 23678 44920 For-profit, group ( 0.55921 0.12463 0.31616 )  
   2) Jobs_reported &lt; 1.5 10134 14150 For-profit, Individual ( 0.29820 0.01944 0.68236 )  
     4) Industry: Accommodation and Food Services,Real Estate and Rental and Leasing,Professional, Scientific, and Technical Services,Construction,Administrative and Support and Waste Management and Remediation Services,Educational Services,Agriculture, Forestry, Fishing and Hunting,Health Care and Social Assistance,Retail Trade,Information,Arts, Entertainment, and Recreation,Management of Companies and Enterprises,Public Administration,Finance and Insurance,Manufacturing,Wholesale Trade,Utilities 7146 10320 For-profit, Individual ( 0.37014 0.01301 0.61685 ) *
     5) Industry: Other Services (except Public Administration),Transportation and Warehousing 2988  3139 For-profit, Individual ( 0.12617 0.03481 0.83902 ) *
   3) Jobs_reported &gt; 1.5 13544 18150 For-profit, group ( 0.75450 0.20334 0.04216 )  
     6) Industry: Accommodation and Food Services,Real Estate and Rental and Leasing,Professional, Scientific, and Technical Services,Construction,Administrative and Support and Waste Management and Remediation Services,Agriculture, Forestry, Fishing and Hunting,Health Care and Social Assistance,Retail Trade,Information,Management of Companies and Enterprises,Finance and Insurance,Manufacturing,Wholesale Trade,Transportation and Warehousing,Mining, Quarrying, and Oil and Gas Extraction 10047  9035 For-profit, group ( 0.87927 0.07246 0.04827 )  
      12) Industry: Accommodation and Food Services,Real Estate and Rental and Leasing,Construction,Retail Trade,Manufacturing,Wholesale Trade,Transportation and Warehousing 4818  2377 For-profit, group ( 0.94458 0.01515 0.04027 ) *
      13) Industry: Professional, Scientific, and Technical Services,Administrative and Support and Waste Management and Remediation Services,Agriculture, Forestry, Fishing and Hunting,Health Care and Social Assistance,Information,Management of Companies and Enterprises,Finance and Insurance,Mining, Quarrying, and Oil and Gas Extraction 5229  6112 For-profit, group ( 0.81909 0.12526 0.05565 ) *
     7) Industry: Other Services (except Public Administration),Educational Services,Arts, Entertainment, and Recreation,Public Administration,Utilities 3497  5415 Non-Profit ( 0.39605 0.57935 0.02459 ) *</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(tree_final)</span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(tree_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Presentation_Code_Compiled_files/figure-html/initial_tree-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>cv_tree_ppp <span class="ot">&lt;-</span> <span class="fu">cv.tree</span>(tree_final, <span class="at">K =</span> <span class="dv">10</span>, <span class="at">FUN =</span> prune.misclass)</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>cv_tree_ppp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$size
[1] 5 3 2 1

$dev
[1]  5917  5917  6544 10437

$k
[1] -Inf    0  641 3893

$method
[1] "misclass"

attr(,"class")
[1] "prune"         "tree.sequence"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">x =</span> cv_tree_ppp<span class="sc">$</span>size, <span class="at">y =</span> cv_tree_ppp<span class="sc">$</span>dev <span class="sc">/</span> <span class="fu">nrow</span>(ppp_c))</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(x, y), <span class="at">data =</span> df) <span class="sc">+</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cross-validation error rate vs. tree size"</span>,</span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"CV Error Rate"</span>,</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Tree Size"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Presentation_Code_Compiled_files/figure-html/tree_cv-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>cv_tree_ppp<span class="sc">$</span>size[<span class="fu">which.min</span>(cv_tree_ppp<span class="sc">$</span>dev)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>new_tree <span class="ot">&lt;-</span> <span class="fu">prune.tree</span>(tree_final, <span class="at">best =</span> <span class="dv">5</span>)</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>new_tree</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>node), split, n, deviance, yval, (yprob)
      * denotes terminal node

 1) root 23678 44920 For-profit, group ( 0.55921 0.12463 0.31616 )  
   2) Jobs_reported &lt; 1.5 10134 14150 For-profit, Individual ( 0.29820 0.01944 0.68236 )  
     4) Industry: Accommodation and Food Services,Real Estate and Rental and Leasing,Professional, Scientific, and Technical Services,Construction,Administrative and Support and Waste Management and Remediation Services,Educational Services,Agriculture, Forestry, Fishing and Hunting,Health Care and Social Assistance,Retail Trade,Information,Arts, Entertainment, and Recreation,Management of Companies and Enterprises,Public Administration,Finance and Insurance,Manufacturing,Wholesale Trade,Utilities 7146 10320 For-profit, Individual ( 0.37014 0.01301 0.61685 ) *
     5) Industry: Other Services (except Public Administration),Transportation and Warehousing 2988  3139 For-profit, Individual ( 0.12617 0.03481 0.83902 ) *
   3) Jobs_reported &gt; 1.5 13544 18150 For-profit, group ( 0.75450 0.20334 0.04216 )  
     6) Industry: Accommodation and Food Services,Real Estate and Rental and Leasing,Professional, Scientific, and Technical Services,Construction,Administrative and Support and Waste Management and Remediation Services,Agriculture, Forestry, Fishing and Hunting,Health Care and Social Assistance,Retail Trade,Information,Management of Companies and Enterprises,Finance and Insurance,Manufacturing,Wholesale Trade,Transportation and Warehousing,Mining, Quarrying, and Oil and Gas Extraction 10047  9035 For-profit, group ( 0.87927 0.07246 0.04827 )  
      12) Industry: Accommodation and Food Services,Real Estate and Rental and Leasing,Construction,Retail Trade,Manufacturing,Wholesale Trade,Transportation and Warehousing 4818  2377 For-profit, group ( 0.94458 0.01515 0.04027 ) *
      13) Industry: Professional, Scientific, and Technical Services,Administrative and Support and Waste Management and Remediation Services,Agriculture, Forestry, Fishing and Hunting,Health Care and Social Assistance,Information,Management of Companies and Enterprises,Finance and Insurance,Mining, Quarrying, and Oil and Gas Extraction 5229  6112 For-profit, group ( 0.81909 0.12526 0.05565 ) *
     7) Industry: Other Services (except Public Administration),Educational Services,Arts, Entertainment, and Recreation,Public Administration,Utilities 3497  5415 Non-Profit ( 0.39605 0.57935 0.02459 ) *</code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(new_tree)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(new_tree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Presentation_Code_Compiled_files/figure-html/tree_prune-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a>new_tree <span class="ot">&lt;-</span> <span class="fu">prune.tree</span>(tree_final, <span class="at">best =</span> <span class="dv">3</span>)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>new_tree</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>node), split, n, deviance, yval, (yprob)
      * denotes terminal node

1) root 23678 44920 For-profit, group ( 0.55921 0.12463 0.31616 )  
  2) Jobs_reported &lt; 1.5 10134 14150 For-profit, Individual ( 0.29820 0.01944 0.68236 ) *
  3) Jobs_reported &gt; 1.5 13544 18150 For-profit, group ( 0.75450 0.20334 0.04216 )  
    6) Industry: Accommodation and Food Services,Real Estate and Rental and Leasing,Professional, Scientific, and Technical Services,Construction,Administrative and Support and Waste Management and Remediation Services,Agriculture, Forestry, Fishing and Hunting,Health Care and Social Assistance,Retail Trade,Information,Management of Companies and Enterprises,Finance and Insurance,Manufacturing,Wholesale Trade,Transportation and Warehousing,Mining, Quarrying, and Oil and Gas Extraction 10047  9035 For-profit, group ( 0.87927 0.07246 0.04827 ) *
    7) Industry: Other Services (except Public Administration),Educational Services,Arts, Entertainment, and Recreation,Public Administration,Utilities 3497  5415 Non-Profit ( 0.39605 0.57935 0.02459 ) *</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(new_tree)</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(new_tree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Presentation_Code_Compiled_files/figure-html/tree_prune-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Cross validated error rates are the lowest in trees with nodes 3 and up. The <code>which.min()</code> suggested that the lowest error came at 5 terminal nodes. This is the same size tree as the original output given to us by <code>tree()</code> . 2 nodes can be pruned because they have the same prediction after the node splits. So our final tree has 3 nodes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(tree_final)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
tree(formula = type_mod ~ ., data = ppp_c)
Variables actually used in tree construction:
[1] "Jobs_reported" "Industry"     
Number of terminal nodes:  5 
Residual mean deviance:  1.156 = 27370 / 23670 
Misclassification error rate: 0.2493 = 5903 / 23678 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(new_tree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Classification tree:
snip.tree(tree = tree_final, nodes = c(6L, 2L))
Variables actually used in tree construction:
[1] "Jobs_reported" "Industry"     
Number of terminal nodes:  3 
Residual mean deviance:  1.208 = 28600 / 23680 
Misclassification error rate: 0.2493 = 5903 / 23678 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">1234</span>)</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>Z <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(ppp_c), <span class="fu">nrow</span>(ppp_c)<span class="sc">/</span><span class="dv">2</span>)</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>bag <span class="ot">&lt;-</span> randomForest<span class="sc">::</span><span class="fu">randomForest</span>(type_mod <span class="sc">~</span> Jobs_reported <span class="sc">+</span> Industry, <span class="at">data =</span> ppp_c[Z,])</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>bag</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
 randomForest(formula = type_mod ~ Jobs_reported + Industry, data = ppp_c[Z,      ]) 
               Type of random forest: classification
                     Number of trees: 500
No. of variables tried at each split: 1

        OOB estimate of  error rate: 24.43%
Confusion matrix:
                       For-profit, group Non-Profit For-profit, Individual
For-profit, group                   4642        484                   1528
Non-Profit                           498        876                    106
For-profit, Individual               246         30                   3429
                       class.error
For-profit, group       0.30237451
Non-Profit              0.40810811
For-profit, Individual  0.07449393</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>Yhat <span class="ot">&lt;-</span> <span class="fu">predict</span>(bag, <span class="at">newdata =</span> ppp_c[<span class="sc">-</span>Z,])</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(Yhat, ppp_c<span class="sc">$</span>type_mod[<span class="sc">-</span>Z])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        
Yhat                     For-profit, group Non-Profit For-profit, Individual
  For-profit, group                   4566        477                    268
  Non-Profit                           527        903                     27
  For-profit, Individual              1494         91                   3486</code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(Yhat <span class="sc">!=</span> ppp_c<span class="sc">$</span>type_mod[<span class="sc">-</span>Z])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2436017</code></pre>
</div>
</div>
<p>Our tree produced a training OOB Error Rate of 24.36%.</p>
</section>
</section>
<section id="comparing-methods" class="level2">
<h2 class="anchored" data-anchor-id="comparing-methods">Comparing Methods</h2>
<section id="regression-1" class="level3">
<h3 class="anchored" data-anchor-id="regression-1">Regression</h3>
<table class="table">
<thead>
<tr class="header">
<th>Method</th>
<th>MSE</th>
<th>Predictors</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Stepwise</td>
<td>2106947766</td>
<td>12</td>
</tr>
<tr class="even">
<td>Ridge</td>
<td>3777754837</td>
<td>40</td>
</tr>
<tr class="odd">
<td>LASSO</td>
<td>2002900584</td>
<td>4</td>
</tr>
<tr class="even">
<td>PCR</td>
<td>2041329571</td>
<td>40</td>
</tr>
<tr class="odd">
<td>PLS</td>
<td>2040856908</td>
<td>11</td>
</tr>
</tbody>
</table>
</section>
<section id="classification-1" class="level3">
<h3 class="anchored" data-anchor-id="classification-1">Classification</h3>
<table class="table">
<thead>
<tr class="header">
<th>Method</th>
<th>Error Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>KNN</td>
<td>32.3%</td>
</tr>
<tr class="even">
<td>LDA</td>
<td>35.76%</td>
</tr>
<tr class="odd">
<td>QDA*</td>
<td>55.88%</td>
</tr>
<tr class="even">
<td>Tree</td>
<td>24.36%</td>
</tr>
</tbody>
</table>
<p>*Removed <code>Race</code>, <code>Industry</code>, and <code>Age of Business</code> due to rank deficiency.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>