---
title: "Group Project Plan"
author: "M. Lewis, P. Magee, M. Willis, and E. Wong"
format: html
editor: visual
---

```{r message=FALSE}
library(tidyverse)
```

# Project Title:

Predicting the Foregiveness of Paycheck Protection Program (PPP) Loans in Washington, DC.

# Group Members

-   Michael Lewis

-   Peter Magee

-   Margaret Willis

-   Ethan Wong

# Topic

Using a data set tracking PPP loans, we seek to develop and tune models that predict whether a loans in Washington, DC will be foregiven.

# Questions of Interest

### Regression:

-   Assess the relationship between.....I haven't looked at the data set yet....

### Classification:

-   What methods have the lowest MSE for the correct prediction of whether loans will be foregiven?

# Approaches

-   I am thinking we mention a few methods and what we hope to attain in using them?

# Group Responsibilities

-   Maintain/submit Github

-   Maybe one person who reaches out to professor whenever we have a question?

-   Formatting poster (assuming we wish to go that route).

-   Assuming how many/which strategies we want to use i figure we can each take one or two.

# Deliverable

-   I believe we said a poster.
